package internal

import (
	"strings"
	"testing"

	"github.com/sqlc-dev/plugin-sdk-go/metadata"
	"github.com/sqlc-dev/plugin-sdk-go/plugin"
)

// gadgetReq builds a minimal one-table/one-query request, optionally with a
// file_header and emit_init_file.
func gadgetReq(fileHeader string, emitInit bool) *plugin.GenerateRequest {
	header := ""
	if fileHeader != "" {
		header = `"file_header": ` + `"` + fileHeader + `",`
	}
	initVal := "false"
	if emitInit {
		initVal = "true"
	}
	return &plugin.GenerateRequest{
		Catalog: &plugin.Catalog{
			DefaultSchema: "public",
			Schemas: []*plugin.Schema{{
				Name: "public",
				Tables: []*plugin.Table{{
					Rel: ident("gadget"),
					Columns: []*plugin.Column{
						{Name: "gadget_id", NotNull: true, Type: &plugin.Identifier{Name: "bigint"}, Table: ident("gadget")},
					},
				}},
			}},
		},
		Queries: []*plugin.Query{{
			Name:     "GetGadget",
			Cmd:      metadata.CmdOne,
			Filename: "queries.sql",
			Text:     "SELECT gadget_id FROM gadget WHERE gadget_id = $1",
			Columns:  []*plugin.Column{{Name: "gadget_id", NotNull: true, Type: &plugin.Identifier{Name: "bigint"}, Table: ident("gadget")}},
			Params:   []*plugin.Parameter{{Number: 1, Column: &plugin.Column{Name: "gadget_id", NotNull: true, Type: &plugin.Identifier{Name: "bigint"}}}},
		}},
		Settings: &plugin.Settings{Engine: "postgresql"},
		PluginOptions: []byte(`{
			"package": "m",
			"sql_driver": "sqlalchemy",
			"model_type": "pydantic",
			"emit_classes": true,
			` + header + `
			"emit_init_file": ` + initVal + `
		}`),
	}
}

// TestFileHeaderOnEveryFile (F5): when file_header is set, the literal is
// absolute line 1 of models.py, the query file, AND __init__.py, immediately
// followed by the sqlc header.
func TestFileHeaderOnEveryFile(t *testing.T) {
	resp, err := Generate(t.Context(), gadgetReq("# pyright: basic", true))
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	want := []string{"models.py", "queries.py", "__init__.py"}
	got := map[string]bool{}
	for _, f := range resp.Files {
		got[f.Name] = true
		first := f.Name + ": " + strings.SplitN(string(f.Contents), "\n", 2)[0]
		if !strings.HasPrefix(string(f.Contents), "# pyright: basic\n# Code generated by sqlc") {
			t.Errorf("%s: file_header must be line 1 before the sqlc header, got first line %q", f.Name, first)
		}
	}
	for _, w := range want {
		if !got[w] {
			t.Errorf("expected %s to be emitted", w)
		}
	}
}

// TestFileHeaderUnsetIsNoOp (F5): with no file_header, every file starts
// directly with the sqlc header (no prepended literal).
func TestFileHeaderUnsetIsNoOp(t *testing.T) {
	resp, err := Generate(t.Context(), gadgetReq("", true))
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	for _, f := range resp.Files {
		if !strings.HasPrefix(string(f.Contents), "# Code generated by sqlc") {
			t.Errorf("%s: unset file_header must be a no-op (sqlc header on line 1)", f.Name)
		}
	}
}

// TestEmitInitFileFalseEmitsNoInit (F5): emit_init_file:false emits no
// __init__.py (app_db's curated init stays hand-managed).
func TestEmitInitFileFalseEmitsNoInit(t *testing.T) {
	resp, err := Generate(t.Context(), gadgetReq("# pyright: basic", false))
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	for _, f := range resp.Files {
		if f.Name == "__init__.py" {
			t.Error("emit_init_file:false must emit no __init__.py")
		}
	}
}
